### ISSUE TITLE
Several metadata gone from META.yaml/json in 0.64

### ISSUE THREAD

**Issue by perlpunk** [davorg-cpan/xml-feed#63]
While updating https://build.opensuse.org/project/show/devel:languages:perl I noticed that several metadata is now missing and thought it might have been accidental:
https://metacpan.org/release/DAVECROSS/XML-Feed-0.64/diff/DAVECROSS/XML-Feed-0.63
abstract, author, license, provides, resources, ...
Also the new version is only in XML/Feed.pm, but the other modules still have 0.63: https://metacpan.org/dist/XML-Feed/source/lib/XML/Feed/Entry.pm#L6

**Comment by davorg** [comment]
Oh. Yes, that's weird. I have a suspicion of what might have caused it. I'll try to get a fixed version out today.

**Comment by davorg** [comment]
Version 0.65 on CPAN now (and will be indexed in the 30 minutes).

https://metacpan.org/release/DAVECROSS/XML-Feed-0.65

(I built yesterday's release with `Makefile.PL` instead of `Build.PL`)

**Comment by perlpunk** [comment]
Thanks!
